---
- debug: var=ansible_os_family
- name: install developer tools in linux distros with apt-get
  apt: name=zsh state=latest force=yes
  when: ansible_os_family == "Debian"

- name: install developer tools in Mac with homebrew package manager
  homebrew: name=zsh state=latest
  when: ansible_os_family == "Darwin"

- name: collect zsh facts 
  shell: echo $SHELL
  register: default_shell
  changed_when: False
  sudo: no

- name: collect zsh facts 
  shell: echo $HOME
  register: default_home
  sudo: no
- debug: var=default_home

- name: install oh-my-zsh
  git: name=https://github.com/robbyrussell/oh-my-zsh.git dest={{default_home.stdout}}/.oh-my-zsh
  register: install_op
  when: default_shell.stdout.find('/bin/zsh') == -1
- debug: var=install_op

- debug: var=templates_path

- name: create template .zshrc at remote
  template: src={{templates_path}}/.zshrc dest={{default_home.stdout}}/.zshrc
  sudo: yes
  when: default_shell.stdout.find('/bin/zsh') == -1

- name: set zsh as default shell
  shell: chsh -s /bin/zsh
  sudo: yes
  when: default_shell.stdout.find('/bin/zsh') == -1

- name: homebrew installations
  homebrew: name=python3
  when: ansible_os_family == "Darwin"