---
- stat: path="{{applications_location}}/Sublime2.app"
  register: sublime_app

- name: "Download Sublime Text 3 Editor"
  get_url: url="{{sublime_url}}" dest="{{download_location}}/sublime.dmg"

- name: Installing Sublime Text
  shell: "{{ item }}"
  with_items:
  - hdiutil mount "{{download_location}}/sublime.dmg"
  - cp -R /Volumes/Sublime\ Text\ 2/Sublime\ Text\ 2.app "{{applications_location}}/Sublime Text.app"
  - hdiutil unmount /Volumes/Sublime\ Text\ 2
  when: sublime_app.stat.exists != True and False

- get_url: url="{{sublime_packagecontrol_url}}" dest=~/Library/Application\ Support/Sublime\ Text\ 2/Installed\ Packages/Package\ Control.sublime-package
