---
- stat: path="{{applications_location}}/Sublime2.app"
  register: sublime_app

- name: "Download Sublime Text 3 Editor"
  get_url: url="http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%202.0.2.dmg" dest="{{download_location}}/sublime.dmg"

- name: Installing Sublime Text
  shell: "{{ item }}"
  with_items:
  - hdiutil mount "{{download_location}}/sublime.dmg"
  - cp -R /Volumes/Sublime\ Text\ 2/Sublime\ Text\ 2.app "{{applications_location}}/Sublime2.app"
  - hdiutil unmount /Volumes/Sublime\ Text\ 2
  when: sublime_app.stat.exists != True
