---
- file: path="~/.vim/bundle" state=directory
- file: path="~/.vim/autoload" state=directory

- shell: curl -LSso ~/.vim/autoload/pathogen.vim https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim

- template: src="{{templates_path}}/.vimrc" dest="~/.vimrc"