---
- file: path="~/.vim/bundle" state=directory
- file: path="~/.vim/autoload" state=directory

- git: name="https://github.com/tpope/vim-pathogen.git" dest="~/.vim/autoload/pathogen.vim"

- template: src="{{templates_path}}/.vimrc" dest="~/.vimrc"