---
- name: collect zsh facts 
  shell: echo $SHELL
  register: default_shell
  changed_when: False

- name: install oh-my-zsh
  git: name=https://github.com/robbyrussell/oh-my-zsh.git dest="~/.oh-my-zsh"
  when: default_shell.stdout.find('/bin/zsh') == -1

- name: create template .zshrc at remote
  template: src="{{templates_path}}/.zshrc" dest="~/.zshrc"

- name: set zsh as default shell
  shell: chsh -s /bin/zsh {{ ansible_ssh_user }}
  when: default_shell.stdout.find('/bin/zsh') == -1
