---
# - shell: subl --version
#   register: sublime_version

# - name: "Download Sublime Text 3 Editor"
#   get_url: url="{{sublime_url}}" dest="{{download_location}}/sublime.dmg"
#   when: False

# - name: Installing Sublime Text
#   shell: "{{ item }}"
#   with_items:
#   - hdiutil mount "{{download_location}}/sublime.dmg"
#   # - cp -R /Volumes/Sublime*/Sublime*.app "{{applications_location}}/Sublime Text.app"
#   - hdiutil unmount /Volumes/Sublime*
#   - cp "{{my_configs_path}}"/*.sublime-keymap ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/
#   when: sublime_version.stdout.find("Sublime Text Build") != -1

# - get_url: url="{{sublime_packagecontrol_url}}" dest=~/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages/Package\ Control.sublime-package

- shell: subl --version
  register: subl_exists

- homebrew_cask: name=sublime-text3
  when: "subl_exists.stdout.find('brew: command not found')!=-1"


# Todo: Copy user-settings file, install package manager
