---
- name: install git
  apt: name=git state=latest force=yes cache_valid_time=3600
- name: clone sample repo 
  git: name=git://github.com/dineshkumar-cse/Test.git dest=/vagrant/test-git accept_hostkey=yes